Removing AWS from the collection and making it general
ansible-middleware/rhbk-datagrid-aws pull request #8
Opened 2024-10-26 15:02 UTC by RanabirChakraborty

Removing AWS from the collection and making it general

2024-10-28 09:19 UTC, guidograzioli requested changes
Please address comment; while you are here, can you also get rid of the "promtail" role and tasks?

2024-10-28 09:19 UTC, guidograzioli commented on README.md
> -[defaults]
let's keep this block, changing "ec2-user" to  "<ssh_user>"

2024-10-28 09:19 UTC, guidograzioli commented on galaxy.yml
> +name: rhbk-ha-cluster
this should be `rhbk_ha_cluster` (no dash allowed in collection FQCN)

2024-10-28 09:19 UTC, guidograzioli commented on inventory/group_vars/eu_central_1.yml
> +aurora_endpoint: rhbk-ha-cluster.cluster-cqy2krcosm24.eu-central-1:5432
because aurora is aws specific, we should rename to "db_" please

2024-10-28 15:26 UTC, RanabirChakraborty commented
@guidograzioli review now.

2024-10-30 16:31 UTC, guidograzioli approved these changes
LGTM

2024-10-30 16:31 UTC, merged